// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jxvkvafudkitketyaorq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4dmt2YWZ1ZGtpdGtldHlhb3JxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NDQ5NTksImV4cCI6MjA2NzEyMDk1OX0.f9f1cgn4LFp0wG4zR6URIpBVJ1JpBQ9PndX1SMfh3m8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});